name: Scheduled fetch games data
on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/1 * * * *'

jobs:
  fetch_games_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run fetch games data
        run: npm run fetchGamesData
        env:
          VERCEL_API_KEY: ${{ secrets.VERCEL_API_KEY }}
