name: Schedule Fetch Games Data
on:
  schedule:
    - cron: '* * * * *'

jobs:
  fetch_games_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Fetch games data and send to Vercel API
        run: node fetchGamesData.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          VERCEL_API_URL: ${{ secrets.VERCEL_API_URL }}
